### ISSUE TITLE
Add Composer manifest

### ISSUE THREAD

**Issue by mbrodala** [mschwemer/fal_recycler#1]
Even if this extension is not added to TER, a Composer manifest should be added, so that people can pull this extension through a `vcs` Composer repository.

Bonus points if you add this extension to Packagist. ;-)

**Comment by mschwemer** [comment]
Accepted ... I will add it.

**Comment by mschwemer** [comment]
Added a composer.json _and_ published it to TER. It's also available on packagist.

I had to check my last blogpost ;-)

**Comment by mbrodala** [comment]
Thanks a lot. Maybe you should update the README now. ;-)

**Comment by mbrodala** [comment]
And could you trigger a re-scan of your package on Packagist? It seems like there are no tags present, thus no stable version to fetch. I went with `typo3-ter/fal-recycler` for now.

**Comment by mschwemer** [comment]
Can you have a look? Should work now ... ( Sorry for the hassle ... it's the first time I do this  ;-) )

**Comment by mbrodala** [comment]
Yes, [looks](https://github.com/mschwemer/fal_recycler/blob/d9c096cf6c74d689816276b047ce7ec85f7d16cf/README.md#installation) [fine](https://packagist.org/packages/marcusschwemer/fal-recycler#1.1.5) now. :-)

**Comment by mbrodala** [comment]
Except a small issue, the extension ends up as `typo3conf/ext/fal-recycler` instead of `typo3conf/ext/fa_recycler`, see #2
